name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        cd theme
        yarn build
        cd ..
    - run: cd demo
    - uses: enriikke/gatsby-gh-pages-action@2.1.1
      with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
